name       : lightsoff
version    : 3.16.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/lightsoff/3.16/lightsoff-3.16.1.tar.xz : 7ec154a85da601a366d11b6b434ae0f631c04753cabca4b6c2223a44d355e892
homepage   : https://wiki.gnome.org/Apps/Lightsoff
license    : GPL-2.0
summary    : Tile based puzzle game
description: |
    Lights Off is a puzzle game, where the objective is to turn off all of the tiles on the board. Each click toggles the state of the clicked tile and its non-diagonal neighbors.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
