name       : lightsoff
version    : 3.26.0
release    : 6
source     :
    - https://download.gnome.org/sources/lightsoff/3.26/lightsoff-3.26.0.tar.xz : d12572bc7b70481320ec90c6130ad794b559a9990d08bef158a1d826aaa35976
homepage   : https://wiki.gnome.org/Apps/Lightsoff
license    : GPL-2.0
component  : games.puzzle
summary    : Tile based puzzle game
description: |
    Lights Off is a puzzle game, where the objective is to turn off all of the tiles on the board. Each click toggles the state of the clicked tile and its non-diagonal neighbors.
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
