name       : lightsoff
version    : 3.34.0
release    : 9
source     :
    - https://download.gnome.org/sources/lightsoff/3.34/lightsoff-3.34.0.tar.xz : daba8cd7950f4258105ebb78c7764f31de479cd205533596ca266c274c02d8fb
homepage   : https://wiki.gnome.org/Apps/Lightsoff
license    : GPL-2.0-only
component  : games.puzzle
summary    : Tile based puzzle game
description: |
    Lights Off is a puzzle game, where the objective is to turn off all of the tiles on the board. Each click toggles the state of the clicked tile and its non-diagonal neighbors.
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
