name       : lightsoff
version    : 3.16.1.1
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/lightsoff/3.16/lightsoff-3.16.1.1.tar.xz : 80113f0e2e16db30b62c699f984f5349907f35078a6f75e6cfdd99cccf964201
homepage   : https://wiki.gnome.org/Apps/Lightsoff
license    : GPL-2.0
summary    : Tile based puzzle game
description: |
    Lights Off is a puzzle game, where the objective is to turn off all of the tiles on the board. Each click toggles the state of the clicked tile and its non-diagonal neighbors.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
